### ISSUE TITLE
Unable to receive new messages 

### ISSUE THREAD

**Issue by imkhubaibraza** [featherbear/facebook-messenger-puppeteer#1]
It's not calling to `api.listen` whenever other users send messages. please update the `api.js` code

**Comment by featherbear** [comment]
Fixed in https://github.com/featherbear/facebook-messenger-puppeteer/commit/4b6e02795f7b9e20b40fa6402c6fc7d4b9c06666 ([v1.1.0](https://github.com/featherbear/facebook-messenger-puppeteer/releases/tag/v1.1.0))
