### ISSUE TITLE
is this implementation still working ?? 

### ISSUE THREAD

**Issue by N0NameN0** [featherbear/facebook-messenger-puppeteer#7]
any update planned ?

**Comment by featherbear** [comment]
Still works for me, feel free to reopen this issue and state what's not working if you're facing issues

**Comment by N0NameN0** [comment]
@featherbear 

![image](https://user-images.githubusercontent.com/1048113/163691713-acc6af75-07ce-484d-a133-0946bfeedf58.png)

as you can see mobile version doesn't seem to provide "message" facilities anymore.
